### ISSUE TITLE
why i get this error when make

### ISSUE THREAD

**Issue by Qoraiche** [chopraaa/rtmpdump-ksv#1]
root@ubuntu-512mb-nyc1-01:/tmp/rtmpdump-ksv# make
make[1]: Entering directory `/tmp/rtmpdump-ksv/librtmp'
gcc -Wall   -DRTMPDUMP_VERSION=\"v2.4\" -DUSE_OPENSSL  -O2 -fPIC   -c -o rtmp.o rtmp.c
make[1]: gcc: Command not found
make[1]: *** [rtmp.o] Error 127
make[1]: Leaving directory `/tmp/rtmpdump-ksv/librtmp'
make: *** [librtmp/librtmp.a] Error 2

**Comment by varunchopra** [comment]
You need to install make first. Run this:

`sudo apt-get install build-essential`

**Comment by varunchopra** [comment]
I've updated the readme with more instructions. Should be clearer now. 

Closing this issue.
