### ISSUE TITLE
Error while make

### ISSUE THREAD

**Issue by bronis75** [chopraaa/rtmpdump-ksv#2]
Hi, 

Im trying to install rtmpdump with ksv patch on debian stretch 9.5 with GNU MAKE 4.1
Here is the output : https://www.hastebin.com/pugokepefe.shell
Any idea ?

**Comment by varunchopra** [comment]
I've updated the readme with more instructions. It has been tested on Ubuntu 16.04 and Debian 8. Should still work for 9.
